-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYkTXFbbYhHSGTsI4
Pfti6zY1sOAO9aZ3YH4uKzKQeCOgCgYIKoZIzj0DAQehRANCAATzGTWRruEgR5j4
/gtT8NurMyeTfg5f59ugrGvcDVrjXVSbSbXTuJs9MgUg3ZK7lCK+TVMaK2Sb2WHD
qSXClatr
-----END PRIVATE KEY-----