# codemagic.yaml
#
# This workflow is designed for building and publishing both iOS and macOS
# release versions of your Flutter app to App Store Connect.
# It leverages Codemagic's automatic code signing using an App Store Connect API Key.

workflows:
  ios-macos-release-build:
    name: iOS & macOS Release Build
    instance_type: mac_mini_m1 # Use a Mac instance for Apple builds (required for iOS/macOS)

    # --- Environment Variables ---
    # These variables configure the build environment.
    environment:
      flutter: stable       # Specifies the Flutter channel to use
      xcode: latest         # Uses the latest available Xcode version on Codemagic
      cocoapods: default    # Uses the default CocoaPods version

      # IMPORTANT: If IOS_BUNDLE_ID is in a variable group named "variables",
      # you must specify the group here.
      groups:
        - variables # <<-- ADD THIS LINE to import variables from your "variables" group

      # Firebase Environment Variables (if your app uses Firebase)
      # These should be in the 'variables' group or another group you import.
      # FLUTTER_APP_FIREBASE_API_KEY: your_api_key
      # FLUTTER_APP_FIREBASE_APP_ID: your_app_id
      # FLUTTER_APP_FIREBASE_MESSAGING_SENDER_ID: your_Messaginger_id
      # FLUTTER_APP_FIREBASE_PROJECT_ID: your_project_id
      # FLUTTER_APP_FIREBASE_STORAGE_BUCKET: your_storage_bucket

    # --- Integrations ---
    # This section links your workflow to the App Store Connect API Key configured in Codemagic UI.
    # It tells Codemagic which key to use for fetching signing files and publishing.
    integrations:
      app_store_connect: "Codemagic Integration Key" # Replace with the exact name of your API key in Codemagic Integrations

    # --- Triggering ---
    # Defines when this workflow should be triggered.
    triggering:
      branch_patterns:
        - pattern: 'main' # Trigger this release build workflow on pushes to the 'main' branch
          include: true

    # --- Build Steps (Scripts) ---
    # The sequence of commands to execute during the build.
    scripts:
      - name: Set up Flutter
        script: |
          # Set the Flutter channel, upgrade, and run doctor for diagnostics
          flutter channel $FLUTTER_CHANNEL
          flutter upgrade
          flutter doctor

      - name: Get dependencies
        script: |
          # Fetch Flutter package dependencies
          flutter pub get

      - name: Install iOS Pods
        script: |
          # Navigate to the iOS project directory and install CocoaPods dependencies
          cd ios
          pod install
          cd .. # Navigate back to the root of the Flutter project

      - name: Fetch iOS and macOS signing files
        script: |
          # Debugging: Print the bundle ID to confirm it's available
          echo "Using Bundle ID for signing: ${IOS_BUNDLE_ID}"
          
          # Fetch iOS App Store Distribution files (certificate and provisioning profile)
          app-store-connect fetch-signing-files "${IOS_BUNDLE_ID}" \
            --type IOS_APP_STORE \
            --create
          
          # Fetch macOS App Store Distribution files (certificate and provisioning profile)
          app-store-connect fetch-signing-files "${IOS_BUNDLE_ID}" \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create

      - name: Build iOS App (IPA)
        script: |
          # Build the iOS application package (IPA) for release.
          flutter build ipa --release \
            --obfuscate --split-debug-info=./debug_info \
            --bundle-id "${IOS_BUNDLE_ID}"

      - name: Build macOS App
        script: |
          # Build the macOS application bundle for release.
          flutter build macos --release \
            --obfuscate --split-debug-info=./debug_info \
            --target-platform macos-x64

    # --- Artifacts ---
    # Specifies which files to save as build artifacts after the workflow completes.
    artifacts:
      - build/ios/Runner.ipa
      - build/macos/Build/Products/Release/*.app.zip

    # --- Publishing ---
    # Configures post-build actions, such as email notifications and App Store Connect uploads.
    publishing:
      email:
        recipients:
          - pegumaxinc@gmail.com
        notify:
          success: true
          failure: true

      # --- App Store Connect Publishing (for iOS) ---
      app_store_connect:
        auth: integration
        # submit_to_testflight: true

      # --- macOS App Store Connect Publishing (Advanced - Placeholder) ---
      # As noted before, macOS App Store publishing can be more complex due to notarization.
      # This YAML will build the macOS app, but full automated notarization/upload might require more.
