# .codemagic.yaml
workflows:
  ios-macos-build:
    name: iOS & macOS Release Build
    instance_type: mac_mini_m1 # Use a Mac instance for Apple builds

    # --- Environment Variables ---
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # Environment variables for Firebase and Apple signing
      # You MUST set these in Codemagic UI under Environment variables -> Secure files
      # Example:
      # FLUTTER_APP_FIREBASE_API_KEY:
      # FLUTTER_APP_FIREBASE_APP_ID:
      # FLUTTER_APP_FIREBASE_MESSAGING_SENDER_ID:
      # FLUTTER_APP_FIREBASE_PROJECT_ID:
      # FLUTTER_APP_FIREBASE_STORAGE_BUCKET:
      #
      # For iOS Code Signing (set these securely in Codemagic UI)
      # These are examples, you'll get actual values from Apple Developer Portal
      # APPLE_ID: your-apple-id@example.com
      # APP_STORE_CONNECT_PRIVATE_KEY: |
      #   -----BEGIN PRIVATE KEY-----
      #   YOUR_PRIVATE_KEY_HERE
      #   -----END PRIVATE KEY-----
      # APP_STORE_CONNECT_KEY_ID: YOUR_KEY_ID
      # APP_STORE_CONNECT_ISSUER_ID: YOUR_ISSUER_ID
      # IOS_BUNDLE_ID: com.yourcompany.studentsuite # Your iOS Bundle ID (must match pubspec.yaml and Xcode)
      # APP_STORE_CONNECT_BUNDLE_ID: com.yourcompany.studentsuite # Same as IOS_BUNDLE_ID
      # CERTIFICATE_PRIVATE_KEY: |
      #   -----BEGIN RSA PRIVATE KEY-----
      #   YOUR_P12_PRIVATE_KEY_HERE
      #   -----END RSA PRIVATE KEY-----


    # --- Triggering Syntax ---
    triggering:
      branch_patterns:
        - pattern: 'main' # Trigger on pushes to the 'main' branch
          include: true
        - pattern: 'feature/*' # Trigger on pushes to any branch named 'feature/anything'
          include: true

    scripts:
      - name: Set up Flutter
        script: |
          flutter channel $FLUTTER_CHANNEL
          flutter upgrade
          flutter doctor
      - name: Get dependencies
        script: flutter pub get

      # Build for iOS
      - name: Build iOS App
        script: |
          # flutter build ios --release --no-codesign # For unsigned testing builds
          # For App Store Connect upload, you'd use Codemagic's built-in signing steps
          flutter build ios --release --obfuscate --split-debug-info=./debug_info

      # Build for macOS
      - name: Build macOS App
        script: |
          flutter build macos --release --obfuscate --split-debug-info=./debug_info

    # --- Artifacts Definition ---
    artifacts:
      - build/ios/Runner.ipa # The iOS App Store / TestFlight distributable
      - build/macos/Build/Products/Release/*.app.zip # The macOS app bundle, zipped for download

    # --- Publishing Section (FIXED) ---
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your actual email
        success: true  # <--- FIXED: Should be a boolean value
        failure: true  # <--- FIXED: Should be a boolean value
        # Add other publishing options (like app_store_connect) here when ready
        # app_store_connect:
        #   # ... your App Store Connect config ...
