// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ZM02Unk2Ny0oydUqkdVdPfiq_9mT_YM',
    appId: '1:749555197585:web:34e5aed5fb3fbf56218130',
    messagingSenderId: '749555197585',
    projectId: 'student-suite-9ae1d',
    authDomain: 'student-suite-9ae1d.firebaseapp.com',
    storageBucket: 'student-suite-9ae1d.firebasestorage.app',
    measurementId: 'G-2LMRSQFX09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWSLfXx__GHZpLHApL59LGaEn5jp1mX4',
    appId: '1:749555197585:android:d99914d409057c66218130',
    messagingSenderId: '749555197585',
    projectId: 'student-suite-9ae1d',
    storageBucket: 'student-suite-9ae1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-I7ym-Y0IFlRaOb-F-h7JxC1otoQ_2k',
    appId: '1:749555197585:ios:d21f45b8ce7fab54218130',
    messagingSenderId: '749555197585',
    projectId: 'student-suite-9ae1d',
    storageBucket: 'student-suite-9ae1d.firebasestorage.app',
    iosBundleId: 'com.example.studentSuite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-I7ym-Y0IFlRaOb-F-h7JxC1otoQ_2k',
    appId: '1:749555197585:ios:d21f45b8ce7fab54218130',
    messagingSenderId: '749555197585',
    projectId: 'student-suite-9ae1d',
    storageBucket: 'student-suite-9ae1d.firebasestorage.app',
    iosBundleId: 'com.example.studentSuite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ZM02Unk2Ny0oydUqkdVdPfiq_9mT_YM',
    appId: '1:749555197585:web:c0819dc148ffb35f218130',
    messagingSenderId: '749555197585',
    projectId: 'student-suite-9ae1d',
    authDomain: 'student-suite-9ae1d.firebaseapp.com',
    storageBucket: 'student-suite-9ae1d.firebasestorage.app',
    measurementId: 'G-4MV2W5QWLE',
  );
}
