# Uncomment this line to define a global platform for your project
platform :ios, '15.0' # Set the minimum iOS deployment target to 15.0

# Flutter Pods
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for your Flutter project's plugins will be added here.
  # This part is automatically managed by Flutter when you run 'flutter pub get'.
  # It looks for a file named '.flutter-plugins' which contains a list of plugins
  # and their corresponding iOS native code paths.
  flutter_application_path = File.expand_path('../.','..', File.dirname(__FILE__))
  load File.join(flutter_application_path, '.flutter-plugins')

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# This post_install hook is necessary for Flutter projects.
# It applies additional build settings to the pods' targets,
# ensuring compatibility with Flutter's build process.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
